@startuml
' アクターの定義
actor "Raspberry Pi" as Raspi
actor "Slack" as Slack
actor "AIサービス" as AIService
actor "データベース" as DB

' サーバをシステムとして定義
rectangle Server {
    usecase "写真撮影とデータ送信" as UC1
    usecase "写真判定処理" as UC2
    usecase "通知送信" as UC3
    usecase "ラズパイ識別子とユーザ管理" as UC4
    usecase "エラー処理" as UC5
}

' アクターとユースケースの関係
Raspi --> UC1
UC1 --> UC2
UC2 --> AIService : 解析リクエスト
AIService --> UC2 : 机の汚さ判定結果を返却
UC2 --> UC3
UC4 --> UC2
UC3 --> Slack
UC1 --> UC5
UC2 --> UC5
UC4 --> DB : クエリ実行
DB --> UC4 : 机の使用者名を返却
UC5 --> UC3
@enduml