- name: Create directory if it does not exist
  file:
    path: /home/ubuntu/okataduke
    state: directory
    mode: '0777'

- name: Copy `okataduke program files` to `~/okataduke`
  ansible.builtin.copy:
    remote_src: no
    src: main.py
    dest: /home/ubuntu/okataduke/main.py
    mode: '0777'